### ISSUE TITLE
Doesn't support slash times with initial values

### ISSUE THREAD

**Issue by palfrey** [nbari/cron-parser#3]
e.g. `0 1/6 * * *` for "every 6h starting from 01:00" doesn't work, because this parser supports `*/<num>` but not `<num>/<num>`. This is supported by Kubernetes cronjobs at least, via the Go cron format (see https://pkg.go.dev/github.com/robfig/cron/v3#hdr-Special_Characters)

Thanks for all the other work here!

**Comment by nbari** [comment]
Hi @palfrey , `0 1,7,13,19 * * * ` Could cover that case (every 6 hours starting at 1), I think it is easier/clearer (less prone to error) any thoughts, use case?

**Comment by nbari** [comment]
hi @palfrey, I just implemented it in [0.10.0](https://github.com/nbari/cron-parser/releases/tag/0.10.0), whenever you have time would appreciate if could test, verify

**Comment by palfrey** [comment]
Sadly, I no longer have access to the use case, because the relevant company both made me redundant and then later went bankrupt. The code _might_ exist, but it's well out of my reach these days.
